name: Greeting
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, World!"
      - name: Instal node with nvm
        run : nvm install node
      - name: Print Node Version
        run: node -v
