name: Greeting
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, World!"
      - name: Install Node
        run: sudo apt install nodejs
      - name: Print Node Version
        run: node -v
