name: Greeting
on: 
  workflow_dispatch: 

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, World!"
  install_node:
    needs: greeting
    runs-on: ubuntu-latest
    steps:
      - name: Instal node with Market place packge
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Print Node Version
        run: node -v
  
